src/website/__init__.py
from flask import Flask

#1 - Je créé l'app, lignes de codes non modifiables-----------------------------------------------------------
def create_app():
    app = Flask(__name__)

#2 - Je m'occupe des Blueprint--------------------------------------------------------------------------------
    #depuis la feuille "views" j'importe la variable views (qui contient le blueprint)
    from .views import views
    #J'enregistre ces Blueprint dans mon app
    app.register_blueprint(views, url_prefix="/")
    
    return app

src/website/views.py
from flask import render_template, Blueprint

views = Blueprint("views", __name__)


@views.route('/')
def home_page():
    return render_template('home.html')

@views.route('/menu-1')
def menu_1():
    return render_template('menu_1.html')

@views.route('/menu-2')
def menu_2():
    return render_template('menu_2.html')

src/website/templates/base.html
<!--tuto : https://youtu.be/Qr4QMBUPxWo?feature=shared&t=3776-->

<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>

    <body>
            <!--Navbar-->
            <!--https://getbootstrap.com/docs/5.3/components/navbar/-->
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                <a class="navbar-brand" href="{{url_for('views.home_page')}}">NFT Website</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.menu_1')}}">Menu 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.menu_2')}}">Menu 2</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" aria-disabled="true">Menu 3</a>
                    </li>
                    </ul>
                </div>
                </div>
            </nav>


            <!--Body content-->
            {% block content %}
            {% endblock %}


            <!--Bootstrap-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>

    <!--Night mode-->
    <style>
        body{
            background-color: #212121;
            color: white;
        }
    </style>

</html>

src/website/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}


{% block content %}
<h1>Home Page</h1>

{% endblock %}

src/website/templates/menu_1.html
{% extends 'base.html' %}

{% block title %}
    Menu 1
{% endblock %}


{% block content %}
<h1>Menu 1</h1>

{% endblock %}

src/website/templates/menu_2.html
{% extends 'base.html' %}

{% block title %}
    Menu 2
{% endblock %}


{% block content %}
<h1>Menu 2</h1>

{% endblock %}